### PR TITLE
Sounds and style

### PR DESCRIPTION
**Pull request by WentworthP**
I added desktop styling to kick in at 601 pixels in width.  Should look fine on ipad I think.

### CODE REVIEW

**Comment by LuisSaybe** [comment]
the mgs alert and ff7 victory ding dong now each appear twice, and there aren't any css changes persisting based on screen size

**Comment by LuisSaybe** [comment]
cmon pearce, get it together

**Comment by WentworthP** [comment]
I can't test locally!!!

On Mar 13, 2018 5:01 PM, "Luis E. Banegas Saybe" <notifications@github.com>
wrote:

cmon pearce, get it together

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LuisSaybe/luissaybe/pull/2#issuecomment-372817058>, or mute
the thread

**Comment by LuisSaybe** [comment]
you can if you believe in yourself

**Comment by WentworthP** [comment]
Fixed the issues that you brought up in your comment.  Thanks for the encouragement.  I believed and got it working.

**Pull request merged**
